apache/pekko-projection

.github/workflows/format.yml

Add github scalafmt check

---

.github/workflows/format.yml

If condition is preventing it from running

Fix scalafmt check

---

.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml
core/src/main/scala/akka/projection/ProjectionBehavior.scala
core/src/main/scala/akka/projection/internal/InternalProjectionState.scala
project/AkkaDisciplinePlugin.scala
project/Dependencies.scala
slick/src/test/scala/akka/projection/slick/SlickProjectionSpec.scala

Update both Scala 2.12 and 2.13 versions and add 2.12 to CI

Update Scala versions and add 2.12 to CI

---

.github/workflows/checks.yml
.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml

Replace setup-scala with setup-java

---

project/PekkoDisciplinePlugin.scala
project/PekkoSnapshotRepository.scala

Rename Akka classes to Pekko

---

build.sbt
project/plugins.sbt

Integrate pekko-sbt-paradox

---

.asf.yaml

As discussed in mailing list, this PR mandates a single approving PR review before a PR can be merged.

Require single approving review

---

.asf.yaml

Adds required status checks which is the same as pekko-core (see https://github.com/apache/incubator-pekko/blob/main/.asf.yaml#L32-L38)

Add required status checks

---

.github/actions/sync-nightlies/action.yml
.github/workflows/publish-nightly.yml

Same implementation that was taken from pekko-http

Publish docs

---

project/Dependencies.scala

follow up to https://github.com/apache/incubator-pekko/pull/273

jackson 2.14.2

---

build.sbt
project/PekkoSnapshotRepository.scala
project/build.properties
project/plugins.sbt

Latest version of sbt now has Apache snapshots repo already included

Use ApacheMavenSnapshotsRepo constant

---

eventsourced/src/main/scala/org/apache/pekko/projection/eventsourced/javadsl/EventSourcedProvider.scala

Fix laodEventQuery typo

---

cassandra/src/it/java/org/apache/pekko/projection/cassandra/CassandraProjectionTest.java
cassandra/src/it/scala/org/apache/pekko/projection/cassandra/CassandraOffsetStoreSpec.scala
cassandra/src/it/scala/org/apache/pekko/projection/cassandra/CassandraProjectionSpec.scala
cassandra/src/main/scala/org/apache/pekko/projection/cassandra/javadsl/CassandraProjection.scala
core/src/main/scala/org/apache/pekko/projection/internal/HandlerAdapter.scala
core/src/main/scala/org/apache/pekko/projection/internal/SourceProviderAdapter.scala
core/src/main/scala/org/apache/pekko/projection/javadsl/ProjectionManagement.scala
durable-state/src/main/scala/org/apache/pekko/projection/state/javadsl/DurableStateSourceProvider.scala
eventsourced/src/main/scala/org/apache/pekko/projection/eventsourced/javadsl/EventSourcedProvider.scala
jdbc/src/main/scala/org/apache/pekko/projection/jdbc/javadsl/JdbcProjection.scala
kafka/src/main/scala/org/apache/pekko/projection/kafka/internal/KafkaSourceProviderImpl.scala
project/Dependencies.scala
testkit/src/main/scala/org/apache/pekko/projection/testkit/internal/TestOffsetStoreAdapter.scala
testkit/src/main/scala/org/apache/pekko/projection/testkit/internal/TestSourceProviderImpl.scala
testkit/src/main/scala/org/apache/pekko/projection/testkit/javadsl/TestSourceProvider.scala
testkit/src/test/java/org/apache/pekko/projection/testkit/javadsl/ProjectionTestKitTest.java

Apply compat changes from latest Pekko

---

docs/src/main/paradox/cassandra.md
project/PekkoDisciplinePlugin.scala

* see https://github.com/apache/incubator-pekko-projection/pull/36#pullrequestreview-1423702006
* pekko-connectors docs not yet published but will be in time

fix broken link

---

build.sbt
project/plugins.sbt

we use github actions to rsync and not this sbt plugin

remove rsync plugin

---

examples/src/test/java/jdocs/state/CborSerializable.scala

Something that I quickly noticed, death to the semicolons

Remove redundant semicolons

---

.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/unit-tests.yml
cassandra/src/it/scala/org/apache/pekko/projection/cassandra/CassandraOffsetStoreSpec.scala
cassandra/src/it/scala/org/apache/pekko/projection/cassandra/CassandraProjectionSpec.scala
core-test/src/test/scala/org/apache/pekko/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala
examples/src/test/scala/docs/jdbc/JdbcProjectionDocExample.scala
examples/src/test/scala/docs/kafka/KafkaDocExample.scala
examples/src/test/scala/docs/slick/SlickProjectionDocExample.scala
jdbc/src/it/scala/org/apache/pekko/projection/jdbc/JdbcProjectionSpec.scala
jdbc/src/test/scala/org/apache/pekko/projection/jdbc/JdbcOffsetStoreSpec.scala
kafka/src/it/scala/org/apache/pekko/projection/kafka/KafkaSpecBase.scala
kafka/src/test/scala/org/apache/pekko/projection/kafka/internal/KafkaSourceProviderImplSpec.scala
project/Dependencies.scala
slick/src/test/scala/org/apache/pekko/projection/slick/SlickOffsetStoreSpec.scala

Update Scala 2 versions

---

project/Dependencies.scala

based on https://cwiki.apache.org/confluence/display/PEKKO/Testing+with+Pekko+Snapshot+Jars

latest pekko snapshots

---

project/Dependencies.scala
testkit/src/main/scala/org/apache/pekko/projection/testkit/internal/TestOffsetStoreAdapter.scala

remove dependency on collection-compat

---

cassandra/src/it/scala/org/apache/pekko/projection/cassandra/CassandraProjectionSpec.scala
project/Dependencies.scala

some assertions failed - so I added eventually so that the assertions are retried

match scalatest version used in pekko-testkit

---

project/AddMetaInfLicenseFiles.scala
project/CopyrightHeader.scala
project/MetaInfLicenseNoticeCopy.scala

Same as https://github.com/apache/incubator-pekko/pull/474 but for this repo

Apply normal apache header new files

---

project/Dependencies.scala

including https://github.com/apache/incubator-pekko-projection/security/dependabot/11

upgrade postgres jar to 42.3.8 due to CVEs

---

.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-nightly.yml
docs/src/main/paradox/index.md
docs/src/main/paradox/release-notes.md

add release notes

---

build.sbt
docs/src/main/paradox/index.md
project/LicenseReport.scala
project/plugins.sbt
scripts/link-validator.conf

Add SBT License Report

---

build.sbt
project/AutomaticModuleName.scala

set module name to match what we have in our docs

---

.github/workflows/format.yml
.scalafmt.conf
project/Common.scala

* the mima check was failing in CI until I hardcoded the compare version. This has happened in a few more repos.

re-enable mima

---

.github/workflows/checks.yml
.github/workflows/headers.yml
.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/link-validator.yml
.github/workflows/publish-1.0-docs.yml
.github/workflows/publish-nightly.yml
.github/workflows/unit-tests.yml

see https://github.com/apache/incubator-pekko/pull/1095

upgrade ci actions

---

.github/workflows/link-validator.yml

see https://github.com/apache/incubator-pekko/pull/1104

update action in link-validator.yml

---

project/Dependencies.scala

I've raised https://github.com/apache/incubator-pekko-projection/issues/117 for SqlServer

upgrade db jars used in tests

---

project/plugins.sbt

I want to cut a 1.0.x branch soon and it's possible we will want a 1.1.0-M1 release soon

update build plugins

---

build.sbt

See discussion at https://github.com/apache/incubator-pekko-projection/issues/110 for why

Remove SemVer from Slick module

---

project/Dependencies.scala

version used in pekko 1.1
I intend to only merge this once we have a separate 1.0.x branch for this repo.

jackson 2.16

---

build.sbt

cherry pick 294d87210b4ef89f8968c468382a18b2ecb33f96 #124

remove incubator footer (#124)

---

jdbc/src/it/scala/org/apache/pekko/projection/jdbc/JdbcContainerOffsetStoreSpec.scala
slick/src/it/scala/org/apache/pekko/projection/slick/SlickContainerOffsetStoreSpec.scala

close https://github.com/apache/pekko-projection/issues/129

mssqlserver container should acceptLicense

---

.github/workflows/format.yml

(cherry picked from commit deb3e6f5db9fe91e180bb601b7f88826864a946e)

Update scalafmt-native github action (#143)

---

.scala-steward.conf

see https://github.com/apache/pekko-connectors-kafka/pull/171 and https://github.com/apache/pekko/issues/1202

pin-jackson-2.16

---

build.sbt
project/plugins.sbt

see https://github.com/apache/pekko-connectors/pull/633

add pekko projection bom

---

.scala-steward.conf

pin hibernate in .scala-steward.conf

---

docs/src/main/paradox/cassandra.md

Fix Pekkp typo in cassandra.md

---

.scala-steward.conf

Would have prevented #176 and #175

fix: fix scala-steward configuration

---

.scala-steward.conf

pin h2 in .scala-steward.conf

---

project/Dependencies.scala

new release of pekko-persistence-cassandra

pekko-persistence-cassandra 1.1.0-M1

---

docs/src/main/paradox/index.md
docs/src/main/paradox/release-notes/index.md
docs/src/main/paradox/release-notes/releases-1.0.md
docs/src/main/paradox/release-notes/releases-1.1.md

add release notes for Pekko Projection 1.1.0-M1

---

project/Dependencies.scala

switch to 1.1. links

---

cassandra/src/it/scala/org/apache/pekko/projection/cassandra/ContainerSessionProvider.scala

test with cassandra 5.0.1 (latest docker image)

---

.scala-steward.conf

Pin slick to 3.5.1

---

testkit/src/test/scala/org/apache/pekko/projection/testkit/scaladsl/ProjectionTestKitSpec.scala

increase timeouts in ProjectionTestKitSpec

---

container-license-acceptance.txt
jdbc/src/it/scala/org/apache/pekko/projection/jdbc/JdbcContainerOffsetStoreSpec.scala
slick/src/it/scala/org/apache/pekko/projection/slick/SlickContainerOffsetStoreSpec.scala

* https://hub.docker.com/r/microsoft/mssql-server
* #261

try newer mssql image

---

.asf.yaml

opens up main branch for 2.0.0 dev

protect 1.1.x and 1.2.x branches

---

.github/workflows/checks.yml
.github/workflows/integration-tests-cassandra.yml
.github/workflows/integration-tests-jdbc.yml
.github/workflows/integration-tests-kafka.yml
.github/workflows/integration-tests-slick.yml
.github/workflows/nightly-pekko-1.0-tests.yml
.github/workflows/unit-tests.yml
cassandra-test/src/test/java/org/apache/pekko/projection/cassandra/CassandraProjectionTest.java
cassandra-test/src/test/scala/org/apache/pekko/projection/cassandra/CassandraOffsetStoreSpec.scala
cassandra-test/src/test/scala/org/apache/pekko/projection/cassandra/CassandraProjectionSpec.scala
cassandra/src/main/scala/org/apache/pekko/projection/cassandra/javadsl/CassandraProjection.scala
core/src/main/scala/org/apache/pekko/projection/ProjectionId.scala
core/src/main/scala/org/apache/pekko/projection/internal/HandlerAdapter.scala
core/src/main/scala/org/apache/pekko/projection/internal/SourceProviderAdapter.scala
core/src/main/scala/org/apache/pekko/projection/internal/Telemetry.scala
core/src/main/scala/org/apache/pekko/projection/javadsl/ProjectionManagement.scala
durable-state/src/main/scala/org/apache/pekko/projection/state/javadsl/DurableStateSourceProvider.scala
eventsourced/src/main/scala/org/apache/pekko/projection/eventsourced/javadsl/EventSourcedProvider.scala
jdbc/src/main/scala/org/apache/pekko/projection/jdbc/internal/JdbcHandlerAdapter.scala
jdbc/src/main/scala/org/apache/pekko/projection/jdbc/javadsl/JdbcProjection.scala
kafka/src/main/scala/org/apache/pekko/projection/kafka/internal/KafkaSourceProviderImpl.scala
kafka/src/main/scala/org/apache/pekko/projection/kafka/javadsl/KafkaSourceProvider.scala
project/Dependencies.scala
project/project-info.conf
slick/src/main/scala/org/apache/pekko/projection/slick/internal/SlickOffsetStore.scala
testkit/src/main/scala/org/apache/pekko/projection/testkit/internal/TestOffsetStoreAdapter.scala
testkit/src/main/scala/org/apache/pekko/projection/testkit/internal/TestSourceProviderImpl.scala
testkit/src/test/java/org/apache/pekko/projection/testkit/javadsl/ProjectionTestKitTest.java

drop scala 2.12
