apache/pekko-projection

- docs/release-train-issue-template.md
- docs/src/main/paradox/actor.md
- docs/src/main/paradox/cassandra.md
- docs/src/main/paradox/classic.md
- docs/src/main/paradox/durable-state.md
- docs/src/main/paradox/eventsourced.md
- docs/src/main/paradox/flow.md
- docs/src/main/paradox/getting-started/event-generator-app.md
- docs/src/main/paradox/getting-started/index.md
- docs/src/main/paradox/getting-started/running-cluster.md
- docs/src/main/paradox/getting-started/running.md
- docs/src/main/paradox/getting-started/setup-your-app.md
- docs/src/main/paradox/getting-started/source-provider.md
- docs/src/main/paradox/getting-started/testing.md
- docs/src/main/paradox/jdbc.md
- docs/src/main/paradox/kafka.md
- docs/src/main/paradox/overview.md
- docs/src/main/paradox/projection-settings.md
- docs/src/main/paradox/running.md
- docs/src/main/paradox/slick.md
- docs/src/main/paradox/testing.md
- docs/src/main/paradox/use-cases.md
- examples/src/test/java/jdocs/guide/EventGeneratorApp.java
- examples/src/test/scala/docs/guide/EventGeneratorApp.scala
- projection-core/src/main/resources/reference.conf
* the akka spanner lib was never released (https://github.com/akka/akka-projection/issues/774)
* update a few doc refs and links to use Pekko name
> remove spanner docs and change some Akka refs to Pekko

- .asf.yaml
This puts `required_pull_request_reviews` to correct area, currently its not doing anything
> Move required_pull_request_reviews to correct area

- project/AddMetaInfLicenseFiles.scala
- project/Common.scala
- project/plugins.sbt
Updates sbt-apache-sonatype. Note that this new version renames `SonatypeApachePlugin` to `ApacheSonatypePlugin` to be consistent with the project name.
> Update sbt-apache-sonatype and handle rename

- project/CopyrightHeader.scala
Unwraps single string interpolation i.e. `s"${something}"` into `s"$something"`. Make sure to do a rebase merge of this PR because I need to add its commit to `.git-blame-ignore-revs`
> Unwrap single string interpolation syntax

- .github/workflows/unit-tests.yml
- build.sbt
- cassandra/src/main/scala/org/apache/pekko/projection/cassandra/internal/CassandraProjectionImpl.scala
- core-test/src/test/scala/org/apache/pekko/projection/internal/HandlerRecoveryImplSpec.scala
- core-test/src/test/scala/org/apache/pekko/projection/internal/metrics/tools/InternalProjectionStateMetricsSpec.scala
- core/src/main/scala/org/apache/pekko/projection/ProjectionBehavior.scala
- core/src/main/scala/org/apache/pekko/projection/ProjectionId.scala
- core/src/main/scala/org/apache/pekko/projection/internal/InternalProjectionState.scala
- core/src/main/scala/org/apache/pekko/projection/internal/ProjectionContextImpl.scala
- jdbc/src/main/scala/org/apache/pekko/projection/jdbc/internal/JdbcProjectionImpl.scala
- project/Common.scala
- project/Dependencies.scala
- testkit/src/main/scala/org/apache/pekko/projection/testkit/internal/TestProjectionImpl.scala
* Slick does not yet support scala3 (in a full release) so the pekko-projection-slick module is not yet supporting scala 3
* pekko-projection-kafka tests need slick - I can split up the project so that the runtime code is separate from the tests - the runtime project will be able to support Scala 3 as a result but the tests will not run on Scala 3 - I will do this in a follow up PR
> scala 3 support

- .github/workflows/checks.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/format.yml
- .github/workflows/headers.yml
- .github/workflows/integration-tests-cassandra.yml
- .github/workflows/integration-tests-jdbc.yml
- .github/workflows/integration-tests-kafka.yml
- .github/workflows/integration-tests-slick.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/unit-tests.yml
The latest version of the checkout github actions now supports a `fetch-tags` flag which does as described, i.e. it will fetch all of our tags which removes the various workarounds that was used before (i.e. manually running `git fetch` command) etc etc, see https://github.com/actions/checkout/pull/579
This will also help in the erroneous errors that we get in CI, i.e. 
```
[error] Failed to derive version from git tags. Maybe run `git fetch --unshallow` or `git fetch upstream` on a fresh git clone from a fork? Derived version: 0.0.0+1-337943bd-SNAPSHOT`
```
> Use fetch tags from latest checkout action

- project/Dependencies.scala
See https://github.com/mdedetrich/akka-projection-apache/blob/main/project/Dependencies.scala#L12-L20 for how the versioning is meant to work.
Also due to the `apiURL` fix in pekko-connectors, the doc links are now fixed (which also means the Link Validator is working).
> Fix versioning in docs

- jdbc/src/test/java/org/apache/pekko/projection/jdbc/JdbcProjectionTest.java
solved: #104
It is the same problem as #105.
> fix flaky JdbcProjectionTest

- .asf.yaml
- .github/workflows/publish-1.0-docs.yml
- build.sbt
* protect 1.0.x branch
* use 1.0.x branch to publish 1.0 docs
* enable scala 2 inliner
> use main branch for 1.1 dev

- jdbc/src/it/scala/org/apache/pekko/projection/jdbc/JdbcContainerOffsetStoreSpec.scala
- project/Dependencies.scala
- slick/src/it/scala/org/apache/pekko/projection/slick/SlickContainerOffsetStoreSpec.scala
cherry pick
https://github.com/apache/pekko-persistence-jdbc/pull/161/files
> upgrade mssql driver

- project/Dependencies.scala
I think we will need to upgrade these together because Slick needs slf4jv2 compliant logback
> upgrade slick and logback dependencies

- kafka-test/src/test/scala/org/apache/pekko/projection/kafka/internal/KafkaSourceProviderImplSpec.scala
Trying to solve #103, I am very doubtful that KafakConsumer will not be consumed evenly from two partitions.
> fix Kafka flaky test

- .scala-steward.conf
Supersedes apache/pekko-projection#135
> scala-steward: pin mssql-jdbc to jdk8 artifacts

- scripts/link-validator.conf
see https://github.com/apache/pekko-projection/actions/runs/9539525770/job/26289975419?pr=173
I am leaving the cassandra links to a different time.
The license report content is not under our control - all we can do is ignore broken links.
see https://github.com/apache/pekko-projection/issues/160
> broken java.net links in license report

- build.sbt
Already set on main branch.
https://github.com/apache/pekko-projection/blob/main/build.sbt#L206
See the footer on https://nightlies.apache.org/pekko/docs/pekko-projection/1.0/docs/
but not on https://nightlies.apache.org/pekko/docs/pekko-projection/1.1/docs/
> remove incubator footer from docs

- project/Protobuf.scala
We have updated to protobuf-java 3.25.5 - seems useful to keep protoc in sync.
> Update protoc to 3.25.5

- build.sbt
- eventsourced/src/main/scala/org/apache/pekko/projection/eventsourced/javadsl/EventSourcedProvider.scala
- eventsourced/src/main/scala/org/apache/pekko/projection/eventsourced/scaladsl/EventSourcedProvider.scala
- eventsourced/src/test/resources/logback-test.xml
- eventsourced/src/test/scala/org/apache/pekko/projection/eventsourced/scaldsl/EventSourcedProviderSpec.scala
- project/Dependencies.scala
- project/PekkoCoreDependency.scala
Pending release of https://github.com/apache/pekko/pull/1518.
> Configuring persistence plugins at runtime for EventSourcedProvider

- .github/workflows/checks.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/format.yml
- .github/workflows/headers.yml
- .github/workflows/integration-tests-cassandra.yml
- .github/workflows/integration-tests-jdbc.yml
- .github/workflows/integration-tests-kafka.yml
- .github/workflows/integration-tests-slick.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-pekko-1.0-tests.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.0-nightly.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/unit-tests.yml
header depends on if the CI job is based on something inherited from Akka or not
> add ci job to publish 1.0 snapshots and add license headers

- eventsourced/src/test/scala/org/apache/pekko/projection/eventsourced/scaldsl/EventSourcedProviderSpec.scala
Resolves https://github.com/apache/pekko-projection/issues/254.
This should be a simple fix for the issue. I think that missing probe calls made it so that setups of different actors got unintentionally executed in parallel, causing their events to get interweaved.
More complex fix for this test, and a one that also better fits how the real implementation of events by slices works, would be to only assert order within persistence ID. We could consider going for that solution now or only if this simpler solution ends up not fixing the issue.
> Fix sequential execution of actor setup in EventSourcedProviderSpec

- project/Protobuf.scala
* matches what we have in other pekko repos
* 3.25.6 generated code avoids some problematic code that used to appear when older protoc is used
* follow up to #210
> protoc 3.25.6

- .scala-steward.conf
Updated configuration to use mssql-jdbc Java 11 artifacts and removed pins for older versions.
> Modify .scala-steward.conf for dependency updates
